# REVISAR HABILIDADES RACIAIS DATA
# Este dicionário contém as habilidades raciais de D&D 5e, com suas descrições.

HABILIDADES_RACIAIS_DATA = {
    "Visão no Escuro":"Uma criatura com visão no escuro pode enxergar no escuro até uma distância de 18 metros como se fosse luz plena, e no escuro total como se fosse penumbra. Ela não consegue discernir cores no escuro, apenas tons de cinza.",
    "Resistência Anã":"Você tem vantagem em testes de resistência contra veneno e resistência a dano de veneno.",
    "Treinamento em Combate Anão":"Você tem proficiência com machados de batalha, machadinhas, martelos leves e martelos de guerra.",
    "Proficiência em Ferramentas Anãs":"Você ganha proficiência com a ferramenta de artesão à sua escolha: ferramentas de um cervejeiro, ferramentas de um ferreiro ou ferramentas de um pedreiro.",
    "Especialização em Pedra":"Sempre que você realizar um teste de Inteligência (História) relacionado à origem de trabalhos em pedra, você é considerado proficiente na perícia História e adiciona o dobro do seu bônus de proficiência ao teste, em vez do seu bônus de proficiência normal.",
    "Coragem Halfling":"Você tem vantagem em testes de resistência contra ser amedrontado.",
    "Agilidade Halfling":"Você pode mover-se através do espaço de qualquer criatura que seja uma categoria de tamanho maior que a sua.",
    "Fortitude Robusta":"Você tem vantagem em testes de resistência contra veneno e resistência a dano de veneno.",
    "Ancestralidade Feérica":"Você tem vantagem em testes de resistência contra ser enfeitiçado, e magia não pode te colocar para dormir.",
    "Transe":"Elfos não precisam dormir. Em vez disso, eles meditam profundamente, permanecendo semiconscientes, por 4 horas por dia. O que é feito nesse transe concede o mesmo benefício que 8 horas de sono para um humano. Você não precisa dormir e magia não pode te colocar para dormir.",
    "Treinamento com Armas Élficas":"Você tem proficiência com espadas longas, espadas curtas, arcos curtos e arcos longos.",
    "Magia Alta Élfica":"Você conhece um truque à sua escolha da lista de magias de mago. Inteligência é o seu atributo de conjuração para ele.",
    "Escrita Élfica":"Você é proficiente na escrita élfica.",
    "Treinamento com Armas do Elfo da Floresta":"Você tem proficiência com espadas longas, espadas curtas, arcos curtos e arcos longos.",
    "Pés Ligeiros":"Seu deslocamento de caminhada aumenta para 10,5 metros.",
    "Máscara da Natureza":"Você pode tentar se esconder mesmo quando é apenas levemente obscurecido por folhagem pesada, chuva forte, neve caindo, névoa ou outras causas naturais.",
    "Magia Drow":"Você conhece o truque Luz. Quando você atinge o 3º nível, você pode conjurar a magia Fogo Feérico uma vez por dia. Quando você atinge o 5º nível, você pode conjurar a magia Escuridão uma vez por dia. Carisma é o seu atributo de conjuração para essas magias.",
    "Armamento Drow":"Você tem proficiência com rapieiras, espadas curtas e bestas de mão.",
    "Sensibilidade à Luz Solar":"Você tem desvantagem nas jogadas de ataque e em testes de Sabedoria (Percepção) que dependam da visão quando você, o alvo do seu ataque ou qualquer coisa que você esteja tentando perceber estiver sob luz solar direta.",
    "Idiomas Adicionais":"Você pode falar, ler e escrever um idioma extra à sua escolha.",
    "Versatilidade de Atributo":"Dois outros valores de atributo à sua escolha aumentam em 1.",
    "Ancestral Dracônica":"Você tem ancestralidade dracônica. Escolha um tipo de dragão do Draconatos no Manual do Jogador. Seus atributos de força e carisma aumentam. Você ganha resistência a dano do tipo associado à sua ancestralidade dracônica (ex: dragão vermelho = fogo).",
    "Resistência a Dano Dracônico":"Você tem resistência ao tipo de dano associado à sua ancestralidade dracônica.",
    "Sopro Dracônico":"Você pode usar sua ação para exalar energia mágica. Sua ancestralidade dracônica determina o tamanho, forma e tipo de dano da exalação. Quando você usa sua arma de sopro, cada criatura em sua área deve realizar um teste de resistência, determinado pela sua ancestralidade dracônica. Uma criatura sofre 2d6 de dano nesse teste, ou metade se passar. O dano aumenta para 3d6 no 6º nível, 4d6 no 11º nível e 5d6 no 16º nível. Depois de usar sua arma de sopro, você não pode usá-la novamente até completar um descanso curto ou longo.",
    "Astúcia Gnômica":"Você tem vantagem em todos os testes de resistência de Inteligência, Sabedoria e Carisma contra magia.",
    "Ilusão Menor":"Você conhece o truque Ilusão Menor. Inteligência é o seu atributo de conjuração para ele.",
    "Construtor de Gnomo da Rocha":"Você tem proficiência com ferramentas de artesão (ferramentas de funileiro). Você dobra seu bônus de proficiência em qualquer teste de Inteligência feito para fazer uma avaliação de um objeto mágico.",
    "Engenhoso":"Você pode criar pequenos dispositivos mecânicos.",
    "Visão no Escuro Superior":"Sua visão no escuro tem um raio de 36 metros.",
    "Habilidades Versáteis":"Você ganha proficiência em duas perícias à sua escolha.",
    "Armamento dos Meio-Orcs":"Você tem proficiência com machadinhas, machados de batalha, azagaias, machados de guerra e espadas curtas.",
    "Ameaça Intimidadora":"Você ganha proficiência na perícia Intimidação.",
    "Resistência Implacável":"Quando você é reduzido a 0 pontos de vida mas não é morto imediatamente, você pode cair para 1 ponto de vida em vez disso. Você não pode usar essa característica novamente até completar um descanso longo.",
    "Ataques Selvagens":"Quando você acerta um acerto crítico com um ataque de arma corpo a corpo, você pode rolar um dos dados de dano da arma mais uma vez e adicioná-lo ao dano extra do acerto crítico.",
    "Herança Infernal":"Você conhece o truque Taumaturgia. No 3º nível, você pode conjurar a magia Repreensão Infernal uma vez por dia. No 5º nível, você pode conjurar a magia Escuridão uma vez por dia. Carisma é o seu atributo de conjuração para essas magias.",
    "Resistência ao Fogo":"Você tem resistência a dano de fogo."
}